# Generated by Django 5.0.4 on 2024-05-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('bike_name', models.CharField(blank=True, max_length=255)),
                ('product_size', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('product_image1', models.ImageField(upload_to='product_images/')),
                ('product_image2', models.ImageField(upload_to='product_images/')),
                ('best_seller', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('warranty_features', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('feature1', models.CharField(blank=True, max_length=500)),
                ('feature2', models.CharField(blank=True, max_length=500)),
                ('feature3', models.CharField(blank=True, max_length=500)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
    ]
